name: Python Test
on:
  push:
    branches:
    - master
  pull_request:
    branches-ignore:
    - release

jobs:
  build:
    name: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
